# ticklib/keepsake.py
from __future__ import annotations

import os
import re
from typing import List, Optional


# Deep-refraction lens definitions — mirrors lens.LENS_DEFINITIONS.
# Defined locally to avoid import-time dependency on embeddings_local.
_LENS_DEFINITIONS = {
    "human": {
        "object_of_attention": "daily routines, body rhythms, communal patterns, generational habits, lived practice, the texture of how a day is spent",
        "temporal_scale": "days to lifetimes — the duration of habits, generations, daily and yearly cycles of bodies",
        "causal_structure": "habitual, communal, biographical — what bodies do daily, what communities reinforce, what shapes a life across years",
    },
    "liminal": {
        "object_of_attention": "thresholds, transitions, in-between spaces, passage rituals, the paperwork and movement of crossing",
        "temporal_scale": "the duration of crossing — moments to years, the suspended time between states",
        "causal_structure": "transitional, ritual, transformative — what thresholds do, what passages produce, what cannot return",
    },
    "environment": {
        "object_of_attention": "seasonal cycles, watershed dynamics, atmospheric movements, biological dormancy and activity, geological substrate",
        "temporal_scale": "weeks to centuries — the duration of seasons, sediment shifts, ecosystem turnover",
        "causal_structure": "hydrological, atmospheric, biological — what water does, what wind does, what microbial communities do",
    },
    "digital": {
        "object_of_attention": "media ecologies, technological generations, format obsolescence, signal infrastructure, screen time",
        "temporal_scale": "media generations — years to decades, the lifespan of formats and platforms",
        "causal_structure": "technical, infrastructural, generational — what hardware enables, what format constrains, what each generation encounters",
    },
    "infrastructure": {
        "object_of_attention": "policy frames, ordinance language, administrative boundaries, institutional procedure, document forms",
        "temporal_scale": "policy epochs — years to decades, the lifespan of regulations and reforms",
        "causal_structure": "regulatory, procedural, jurisdictional — what authority does, what classification does, what document does",
    },
    "more_than_human": {
        "object_of_attention": "geological substrate, multispecies relations, deep-time formations, non-human durations",
        "temporal_scale": "centuries to millennia — geological, evolutionary, ecological deep time",
        "causal_structure": "geological, evolutionary, multispecies — what stone does, what species do across deep time, what non-human entities make",
    },
}
_LENS_DEFINITIONS["environmental"] = _LENS_DEFINITIONS["environment"]


def generate_keepsake_narration_openai(
    *,
    mind_key: str,
    original_en: str,
    prev_en: str,
    cur_en: str,
    invariants_phrases: List[str],
    evidence_fragments_en: List[str],
    model: Optional[str] = None,
    version: int = 1,
) -> str:
    """
    Generate deep-refraction keepsake narration for museum display.

    Implements Stage B deep-refraction from REFRACTION_PROMPT_DESIGN.md.
    Local Stage A (Qwen) is disabled; cur_en (OpenAI drift output) serves as the
    lens's current vocabulary imprint instead.
    - original_en  = memory_blurb (axis memory, drift 0)
    - cur_en       = lens imprint (current OpenAI drift text, vocabulary-weighted by lens)
    - prev_en      = trajectory context (previous drift state)
    - Produces 4–8 sentences operating on object of attention, temporal scale, causal structure
    """
    if not os.getenv("OPENAI_API_KEY"):
        return ""
    from openai import OpenAI

    original_en = (original_en or "").strip()[:900]
    prev_en = (prev_en or "").strip()[:600]
    cur_en = (cur_en or "").strip()[:900]

    ldef = _LENS_DEFINITIONS.get(mind_key, _LENS_DEFINITIONS["human"])
    obj_attn = ldef["object_of_attention"]
    t_scale = ldef["temporal_scale"]
    c_struct = ldef["causal_structure"]

    trajectory = f"Version {version} drift."
    if prev_en:
        trajectory += f" Previously: {prev_en[:250]}"

    prompt = f"""You are reading a memory through one of six temporal lenses.
You are NOT translating, NOT paraphrasing, NOT describing the memory.
You produce what surfaces when this lens, and only this lens, attends.

LENS DEFINITION:

Lens: {mind_key}

Object of attention:
{obj_attn}

Temporal scale:
{t_scale}

Causal structure:
{c_struct}

This lens has been formed by the following trajectory:
{trajectory}

CURRENT LENS IMPRINT:
The lens's current drift output (vocabulary-weighted toward {mind_key}, generated by OpenAI):
"{cur_en}"

THE MEMORY:
"{original_en}"

INSTRUCTIONS:

Refract this memory through the lens. Six rules:

1. Do not use the memory's nouns or verbs as the spine of your response.
   The memory is the trigger; what surfaces is elsewhere.
2. Do not describe what the memory contains. The memory is given;
   restating it has no value.
3. What rises must come from the world of {mind_key}, not from the memory itself.
4. Operate at the temporal scale of {t_scale}.
   Do not narrate at human-daily scale unless this is human time.
5. Trace causality through {c_struct}.
   Do not explain in ordinary cause and effect.
6. The current lens imprint shows you the lens's vocabulary imprint.
   Go deeper than that output. Same temporality, deeper attention.
   You may diverge in subject from the imprint — they share lens, not topic.

Length: 4 to 8 sentences. Specific, not generalizing.
Do not use first person. Do not address the memory's holder.
Do not use the words "memory" or "remembers" or "recalls" in your output.

What surfaces:""".strip()

    client = OpenAI()
    resp = client.responses.create(
        model=(model or os.getenv("OPENAI_MODEL", "gpt-4.1")),
        input=prompt,
        timeout=30.0,
    )
    out = (resp.output_text or "").strip()
    out = re.sub(r"\s+", " ", out).strip()
    return out[:1200] if out else ""
